
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("message/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("message", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit message</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="objet">Objet</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("objet", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Content</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("content", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date">Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("date", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="idUser">IdUser</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idUser", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="idProjet">IdProjet</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idProjet", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="idFil">IdFil</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idFil", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
