
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("message/new", "Create message")) ?>
</div>

<?php echo $this->tag->form(array("message/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search message</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="objet">Objet</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("objet", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="content">Content</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("content", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date">Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("date", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="idUser">IdUser</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idUser", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="idProjet">IdProjet</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idProjet", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="idFil">IdFil</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idFil", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
