<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("message/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("message/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Objet</th>
            <th>Content</th>
            <th>Date</th>
            <th>IdUser</th>
            <th>IdProjet</th>
            <th>IdFil</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $message) { ?>
        <tr>
            <td><?php echo $message->id ?></td>
            <td><?php echo $message->objet ?></td>
            <td><?php echo $message->content ?></td>
            <td><?php echo $message->date ?></td>
            <td><?php echo $message->idUser ?></td>
            <td><?php echo $message->idProjet ?></td>
            <td><?php echo $message->idFil ?></td>
            <td><?php echo $this->tag->linkTo(array("message/edit/" . $message->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("message/delete/" . $message->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("message/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("message/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("message/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("message/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
