
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("projet/new", "Create projet")) ?>
</div>

<?php echo $this->tag->form(array("projet/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search projet</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="nom">Nom</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nom", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="description">Description</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("description", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="dateLancement">DateLancement</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("dateLancement", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="dateFinPrevue">DateFinPrevue</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("dateFinPrevue", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="idClient">IdClient</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idClient", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
