<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("projet/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("projet/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Description</th>
            <th>DateLancement</th>
            <th>DateFinPrevue</th>
            <th>IdClient</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $projet) { ?>
        <tr>
            <td><?php echo $projet->id ?></td>
            <td><?php echo $projet->nom ?></td>
            <td><?php echo $projet->description ?></td>
            <td><?php echo $projet->dateLancement ?></td>
            <td><?php echo $projet->dateFinPrevue ?></td>
            <td><?php echo $projet->idClient ?></td>
            <td><?php echo $this->tag->linkTo(array("projet/edit/" . $projet->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("projet/delete/" . $projet->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("projet/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("projet/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("projet/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("projet/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
