
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("tache/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("tache", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit tache</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="libelle">Libelle</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("libelle", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date">Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("date", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avancement">Avancement</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avancement", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="codeUseCase">CodeUseCase</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("codeUseCase", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
