
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("tache/new", "Create tache")) ?>
</div>

<?php echo $this->tag->form(array("tache/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search tache</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="libelle">Libelle</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("libelle", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date">Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("date", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avancement">Avancement</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avancement", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="codeUseCase">CodeUseCase</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("codeUseCase", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
