<div class="alert alert-info"><?php echo $nom." [".$user."]" ?></div>
<hr>
<div class="panel panel-info">
    <div class="panel-heading">Détails du projet</div>
    <div class="panel-body">
<?php
    echo "<b>Description: </b><p>".$description."</p>";
    echo "<b>Date de Lancement: </b>".$dateLancement." ";
    echo " <b>Date de Fin prévue: </b>".$dateFinPrevue;
?>
    </div>
</div>
<hr>
<div class="panel panel-info">
    <div class="panel-heading">Equipe</div>
    <div class="panel-body">
        <div id="detailProject">
            <table>
            <?php
                for($i=0; $i<sizeof($tab_usecase); $i++)
                echo "<tr><td>".$tab_usecase[$i]."</td><td>".$tab_poids[$i]."</td><td>".$tab_equipe[$i]."</td></tr>";
            ?>
            <br>
            <?php
                for($i=0; $i<sizeof($tab); $i++)
                echo "<tr><td>".$tab[$i]."</td><td>".$tab2[$i]."</td></tr>";
            ?>
            </table>
        </div>
    </div>
</div>