<div class="alert alert-info"><?php echo $nom." [".$user."]" ?></div>
<hr>
<div class="panel panel-info">
    <div class="panel-heading">Détails du projet</div>
    <div class="panel-body">
<?php
    echo "<b>Description: </b><p>".$description."</p>";
    echo "<b>Date de Lancement: </b>".$dateLancement." ";
    echo " <b>Date de Fin prévue: </b>".$dateFinPrevue;
?>
    </div>
</div>
<hr>
<div class="panel panel-info">
    <div class="panel-heading">Equipe</div>
    <div class="panel-body">
        <div id="detailProject">
            <table class="table table-striped">
                <?php
                foreach($devs as $dev)
                    echo "<tr><td><b>".$dev->getIdentite()."</b> ".$poidsDevs[$dev->getId()]."%</td></tr>";
                ?>
            </table>
        </div>
    </div>
</div>