<div class="alert alert-info"><?php echo $nom . " [" . $user . "]" ?></div>
<hr>
<div class="panel panel-info">
    <div class="panel-heading">Détails du projet</div>
    <div class="panel-body">
        <?php
        echo "<b>Description: </b><p>" . $description . "</p>";
        echo "<b>Date de Lancement: </b>" . $dateLancement . " ";
        echo " <b>Date de Fin prévue: </b>" . $dateFinPrevue;
        ?>
    </div>
</div>
<hr>
<div id="detailProject"></div>
<hr>
<button id="btnMessages" class="btn btn-default">Messages...</button>
<div id="divMessages"></div>
<?php echo $script_foot; ?>