
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("usecase/new", "Create usecase")) ?>
</div>

<?php echo $this->tag->form(array("usecase/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search usecase</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="code">Code</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("code", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="nom">Nom</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nom", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="poids">Poids</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("poids", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avancement">Avancement</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avancement", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="idProjet">IdProjet</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idProjet", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="idDev">IdDev</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("idDev", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
