<h2>Mes projets <?php echo $author->identite ?></h2>
<table class="table">
    <tbody>
    <?php
    var_dump($projects);
    $i = 0;
    foreach ($projects as $project) {
        $j = $i+1;
        echo '<tr>
                <td> ' . $project->nom . '</td>
                <td width="500px">
                <div class="progress">
                  <div class="' . $class[$i] . '" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="min-width: 1.5em;width: ' . $project->avancement . '%">' . $project->avancement . '%
                    <span class="sr-only">' . $project->avancement . '% Complete</span>
                  </div>
                </div>
                </td>
                <td>' . $project->reste . '</td>

                <td> <button class="btnOuvrir btn btn-default" id="btnOuvrir'.$j.'"
                class="btn btn-default">Ouvrir..
                .</button> </td>
        </tr>';
        $i++;
    }
    ?>
    <hr/>
    </tbody>
</table>

<div id='response' ></div>
<div id="equipe"></div>
<?php
echo $script_foot;
?>